# -*- mode: ruby -*-
#vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.define "puppet" do |puppet|
    # Puppetmaster on CentOS 7 
    puppet.vm.box = "centos/7"
  end
  config.vm.define "agent1" do |agent1|
    # Puppet agent on CentOS 7 
    agent1.vm.box = "centos/7"
  end
  config.vm.define "agent2" do |agent2|
    # Puppet agent on Debian
    agent2.vm.box = "debian/jessie64"
  end    
end